<?php

namespace App\Controller;

use Sonata\AdminBundle\Controller\CRUDController;

class ResponseAdminCRUDController extends CRUDController
{
    public function listAction()
    {
        return parent::listAction(); // TODO: Change the autogenerated stub
    }

}