# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  admin.patient:
    class: App\Admin\PatientAdmin
    arguments: [~, App\Entity\Patient, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Patients, label: Liste }
  admin.survey:
    class: App\Admin\SurveyAdmin
    arguments: [~, App\Entity\Survey, ~]
    tags:
      - { name: sonata.admin, manager_type: orm,group: Patients,  label: 'admin.survey.label' }
    calls:
      - [addChild, ['@admin.response', 'survey']]

  admin.response:
    class: App\Admin\ResponseAdmin
    arguments: [~, App\Entity\Response, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Patients,  label: Reponses, show_in_dashboard: false }

  admin.comorbidity:
    class: App\Admin\ComorbidityAdmin
    arguments: [~, App\Entity\Comorbidity, ~]
    tags:
      - { name: sonata.admin, manager_type: orm,group: Configuration,  label: Comorbidity }

  admin.symptom:
    class: App\Admin\SymptomAdmin
    arguments: [~, App\Entity\Symptom, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Configuration, label: Symptom }

  admin.symptompatient:
    class: App\Admin\SymptomPatientAdmin
    arguments: [~, App\Entity\SymptomPatient, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Configuration, label: SymptomPatient , show_in_dashboard: false}
  admin.comorbiditypatient:
    class: App\Admin\ComorbidityPatientAdmin
    arguments: [~, App\Entity\ComorbidityPatient, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Configuration,  label: ComorbidityPatient, show_in_dashboard: false }

  admin.question:
    class: App\Admin\QuestionAdmin
    arguments: [~, App\Entity\Question, ~]
    tags:
      - { name: sonata.admin, manager_type: orm,group: Configuration,  label: Questions }